# Generated by Django 2.1.1 on 2018-11-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.PositiveIntegerField(choices=[(1, 'As fast as possible'), (2, 'In fixed time')], default=1, verbose_name='Answer time')),
                ('answer_start_time', models.TimeField(blank=True, default='08:00', null=True, verbose_name='Start time')),
                ('answer_end_time', models.TimeField(blank=True, default='08:30', null=True, verbose_name='End time')),
                ('mobile', models.CharField(max_length=21, verbose_name='Mobile')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('comment', models.TextField(blank=True, max_length=2048, verbose_name='Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_calls', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Callback',
                'verbose_name_plural': 'Callbacks',
            },
        ),
    ]
